### ISSUE TITLE
Check schema and reference at EUMETSAT

### ISSUE THREAD

**Issue by ikepom** [ceos-wgiss/jupyter-best-practice#5]
Check schema and reference at EUMETSAT and complete [section 4.1.](https://github.com/ceos-wgiss/jupyter-best-practice/blob/main/jupyter-notebook-best-practice-content.md#41-notebook-description-purpose-and-discoverability)

> Notebooks that are considered to be tools require additional descriptive information to make them discoverable for new users. Additional information on input datasets, domain/thematic, application, function and skill level are desirable to ensure that notebooks are targeted at the correct communities. **[ask Ben Loveday for EUMETSAT schema amd reference]**

**Comment by CapeHobbit** [comment]
Below I have attached an example of the schema that we are using for Jupyter Notebook metadata. This example is taken from the following [notebook](https://gitlab.eumetsat.int/eumetlab/oceans/ocean-training/sensors/learn-olci/-/blob/main/1_OLCI_introductory/1_1a_OLCI_data_access_Data_Store.ipynb?ref_type=heads).

[JN_schema_example.json](https://github.com/ceos-wgiss/jupyter-best-practice/files/14881906/JN_schema_example.json)

This json footer is embedded directly from the notebook itself (as per section 4.1), and so there is no need for any further external metadata file. I can provide a general example with annotations on the fields used, if required? Please let me know your preference and I will update section 4.1 accordingly.

**Comment by ikepom** [comment]
Thank you for answering my issue.
But I close this issue because my misunderstanding.
We will talk schema and reference in meeting.
