### ISSUE TITLE
Complete section 4.3 (Technical dependencies and Virtual Environments)

### ISSUE THREAD

**Issue by ikepom** [ceos-wgiss/jupyter-best-practice#6]
We need to complete [section 4.3](https://github.com/ceos-wgiss/jupyter-best-practice/blob/main/jupyter-notebook-best-practice-content.md#43-technical-dependencies-and-virtual-environments)

Update **"Stand alone computer"**, **"JupyterHub deployed on Data Analysis Platform"**, **"OpenDap and http Services"** and **"Zero Install Environments"** sections by existed platforms (listed as follow).

> Google Colabs:
> ESA PGDS
> Get example from Simone Mantovani at Workshop
> Open Data Cube Google Sandbox
> Get example from Brian Killough/Dave Borge
> Earth Analytics Interoperability Lab
> EUMETSAT TrainHub(WGISS-56)
> MAGEO(WGISS-56)

**Comment by CapeHobbit** [comment]
With regards to my contributions on this point, which are focussed on the EUMETSAT TrainHub; in the medium term future, TrainHub's capability will be replaced by those offered by the new EUMETSAT User Portal. However, the latter is not yeat ready.

In the interim, my suggestion is that while I mention both of the above services, I focus my discussion on the [WEkEO Notebook catalogue](https://notebooks.prod.wekeo2.eu/?) as this offers both a discoverable front end for our catalog and a connection to run-time hub services offered on the cloud platform. This uses the same notebooks as offered on TrainHub, with the same metadata schema used for discovery and source linking. Would that be acceptable?

**Comment by ikepom** [comment]
Thank you for answering my issue.
But I close this issue because my misunderstanding.
We will talk schema and reference in meeting.
